apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: wordpress
spec:
  clusterIP: None  # Headless Service, no ClusterIP, to directly access pods
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
