apiVersion: v1
kind: Pod
metadata:
  name: restore-wordpress
spec:
  containers:
  - name: restore
    image: google/cloud-sdk:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Download of WordPress files...";
        gsutil cp gs://wordpress-terraform-extract/wordpress/wordpress_data.tar /mnt/wordpress;
        echo "Extraction...";
        tar -xvzf /mnt/wordpress/wordpress_data.tar -C /mnt/wordpress;
        echo "Finished.";
    volumeMounts:
    - mountPath: /mnt/wordpress
      name: wordpress-storage
  volumes:
  - name: wordpress-storage
    persistentVolumeClaim:
      claimName: wordpress-pvc
  restartPolicy: Never