apiVersion: v1
kind: Pod
metadata:
  name: restore-mariadb
spec:
  containers:
  - name: restore
    image: google/cloud-sdk:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-secret
          key: rootpassword
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Download of MariaDB data...";
        gsutil cp gs://wordpress-terraform-extract/sql/wordpress.sql.gz  /mnt/mariadb-backup;
        echo "Extraction...";
        gunzip /mnt/mariadb-backup/wordpress.sql.gz;
        echo "Import in MariaDB...";
        mysql -h mariadb -u root -p"$MYSQL_ROOT_PASSWORD" wordpress < /mnt/mariadb-backup/wordpress.sql;
        echo "Finished.";
    volumeMounts:
    - mountPath: /mnt/mariadb-backup
      name: mariadb-backup-storage
  volumes:
  - name: mariadb-backup-storage
    persistentVolumeClaim:
      claimName: mariadb-backup-pvc
  restartPolicy: Never
